/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as coreHttp from "@azure/core-http";
import * as operations from "./operations";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import { AzureTableContext } from "./azureTableContext";
import { AzureTableOptionalParams } from "./models";

class AzureTable extends AzureTableContext {
  /**
   * Initializes a new instance of the AzureTable class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param url The URL of the service account or table that is the targe of the desired operation.
   * @param options The parameter options
   */
  constructor(
    credentials: coreHttp.TokenCredential | coreHttp.ServiceClientCredentials,
    url: string,
    options?: AzureTableOptionalParams
  ) {
    super(credentials, url, options);
    this.table = new operations.Table(this);
    this.service = new operations.Service(this);
  }

  table: operations.Table;
  service: operations.Service;
}

// Operation Specifications

export {
  AzureTable,
  AzureTableContext,
  Models as AzureTableModels,
  Mappers as AzureTableMappers,
};
export * from "./operations";
